CREATE TABLE DTQ_USUARIO ( uuId VARCHAR(250) PRIMARY KEY,

name VARCHAR(250) NOT NULL, 
email VARCHAR(250) NOT NULL, 
password VARCHAR(250) NOT NULL, 

created DATE NOT NULL,
modified DATE NOT NULL,
last_login DATE NOT NULL,
token VARCHAR(250) NOT NULL, 
isactive CHAR(1) NOT NULL);

CREATE TABLE DTQ_FRANQUICIA (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(20) 
);

CREATE TABLE DTQ_SUCURSAL (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(20),
	ID_FRANQUICIA NUMBER
);

CREATE TABLE DTQ_PRODUCTO (
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(20),
	CANTIDAD NUMBER,
	ID_SUCURSAL NUMBER
);

